-- 변경사항



--관리자 대출현황 리스트 더미데이터

INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '1', '1', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '1', '2', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '1', '3', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '1', '4', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '1', '5', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '4', '6', '2');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '4', '7', '2');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '4', '8', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '4', '9', '1');
INSERT INTO OVERDUE (OVERDUE_NO, ADMIN_NO, MEMBER_NO, BORROW_NO, STATUS_NO)VALUES (SEQ_OVERDUE_NO.NEXTVAL, '1', '4', '10', '1');






