-- 계정생성

CREATE USER C##DALMAJI IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO C##DALMAJI;
ALTER USER C##DALMAJI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


-------------------------------------------------------------------------

--테이블 삭제 구문
DROP TABLE BORROW CASCADE CONSTRAINTS;
DROP TABLE BOOK_OVERDUE CASCADE CONSTRAINTS;
DROP TABLE BOOK_STATUS CASCADE CONSTRAINTS;


-- 시퀀스 삭제&생성
-- BOOK_BORROW
DROP SEQUENCE SEQ_BOOK_BORROW;
CREATE SEQUENCE SEQ_BOOK_BORROW NOCYCLE NOCACHE;

-- BOOK_OVERDUE
DROP SEQUENCE SEQ_BOOK_OVERDUE;
CREATE SEQUENCE SEQ_BOOK_OVERDUE NOCYCLE NOCACHE;

-- BOOK_STATUS
DROP SEQUENCE SEQ_BOOK_STATUS;
CREATE SEQUENCE SEQ_BOOK_STATUS NOCYCLE NOCACHE;


-- 테이블 생성
-- BOOK_BORROW
CREATE TABLE BOOK_BORROW (
	BORROW_NO	        NUMBER		    PRIMARY KEY
    ,BOOK_NO	        NUMBER		    NOT NULL
    ,MEMBER_NO	        NUMBER		    NOT NULL
    ,BORROW_DATE	    TIMESTAMP	    DEFAULT SYSDATE
    ,DUE_DATE	        TIMESTAMP	    DEFAULT SYSDATE +20
	,RENEW	            TIMESTAMP		
);

COMMENT ON COLUMN "BOOK_BORROW"."BORROW_NO" IS '대여번호';
COMMENT ON COLUMN "BOOK_BORROW"."BOOK_NO" IS '도서번호';
COMMENT ON COLUMN "BOOK_BORROW"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "BOOK_BORROW"."BORROW_DATE" IS '대출일자';
COMMENT ON COLUMN "BOOK_BORROW"."DUE_DATE" IS '반납일자';
COMMENT ON COLUMN "BOOK_BORROW"."RENEW" IS '대출연장';


-- BOOK_OVERDUE
CREATE TABLE BOOK_OVERDUE (
	OVERDUE_NO	            NUMBER		        PRIMARY KEY
	,ADMIN_NO	            NUMBER		        NOT NULL
	,MEMBER_NO	            NUMBER		        NOT NULL
	,BORROW_NO	            NUMBER		        NOT NULL
	,BORROW_STATE	        VARCHAR2(1000)		NOT NULL
	,RESTRICTION_DATE	    VARCHAR2(500)		NOT NULL
);


COMMENT ON COLUMN "BOOK_OVERDUE"."OVERDUE_NO" IS '도서연체번호';
COMMENT ON COLUMN "BOOK_OVERDUE"."ADMIN_NO" IS '관리자번호';
COMMENT ON COLUMN "BOOK_OVERDUE"."USER_NO" IS '회원번호';
COMMENT ON COLUMN "BOOK_OVERDUE"."BORROW_NO" IS '대여번호';
COMMENT ON COLUMN "BOOK_OVERDUE"."BORROW_STATE" IS '대출상태';
COMMENT ON COLUMN "BOOK_OVERDUE"."RESTRICTION_DATE" IS '대출제한기간';



-- BOOK_STATUS
CREATE TABLE BOOK_STATUS (
	STATUS_NO	            NUMBER		        PRIMARY KEY
	,BOOK_STATE	            VARCHAR2(1000)		NOT NULL
);


COMMENT ON COLUMN "BOOK_STATUS"."STATUS_NO" IS '도서상태번호';
COMMENT ON COLUMN "BOOK_STATUS"."BOOK_STATE" IS '도서상태';

키
-- 외래키

ALTER TABLE BOOK_BORROW ADD CONSTRAINT FK_BOOK_LIST_TO_BOOK_BORROW_1 FOREIGN KEY (BOOK_NO) REFERENCES BOOK_LIST (BOOK_NO);
ALTER TABLE BOOK_BORROW ADD CONSTRAINT FK_MEMBER_TO_BOOK_BORROW_1 FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO);
ALTER TABLE BOOK_OVERDUE ADD CONSTRAINT FK_ADMIN_TO_BOOK_OVERDUE_1 FOREIGN KEY (ADMIN_NO) REFERENCES ADMIN (ADMIN_NO);
ALTER TABLE BOOK_OVERDUE ADD CONSTRAINT FK_MEMBER_TO_BOOK_OVERDUE_1 FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO);
ALTER TABLE BOOK_OVERDUE ADD CONSTRAINT FK_BOOK_BORROW_TO_BOOK_OVERDUE_1 FOREIGN KEY (BORROW_NO) REFERENCES BOOK_BORROW (BORROW_NO);
ALTER TABLE BOOK_OVERDUE ADD CONSTRAINT FK_BOOK_STATUS_TO_BOOK_OVERDUE_1 FOREIGN KEY (STATUS_NO) REFERENCES BOOK_STATUS (STATUS_NO);

-- +제경님 부분 BOOK_LIST 외래
ALTER TABLE BOOK_LIST ADD CONSTRAINT FK_BOOK_STATUS_TO_BOOK_LIST_1 FOREIGN KEY (STATUS_NO) REFERENCES BOOK_STATUS (STATUS_NO);



-- 더미데이터 (도서 상태부분)
INSERT INTO BOOK_STATUS (STATUS_NO, BOOK_STATE)
VALUES (SEQ_BOOK_STATUS.NEXTVAL, '대출중');

INSERT INTO BOOK_STATUS (STATUS_NO, BOOK_STATE)
VALUES (SEQ_BOOK_STATUS.NEXTVAL, '연체중');

INSERT INTO BOOK_STATUS (STATUS_NO, BOOK_STATE)
VALUES (SEQ_BOOK_STATUS.NEXTVAL, '반납대기');

INSERT INTO BOOK_STATUS (STATUS_NO, BOOK_STATE)
VALUES (SEQ_BOOK_STATUS.NEXTVAL, '반납완료');








